name: Reusable Workflows

on:
  pull_request:

jobs:
  web-kit-pull-request:
    name: Run Web Kit PR Workflow
    uses: mParticle/mparticle-workflows/.github/workflows/web-kit-pull-request.yml@stable
  pr-branch-check-name:
    name: Check PR for semantic branch name
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-check-name.yml@stable
  pr-title-check:
    name: Check PR for semantic title
    uses: mParticle/mparticle-workflows/.github/workflows/pr-title-check.yml@stable
  pr-branch-target-gitflow:
    name: Check PR for semantic target branch
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-target-gitflow.yml@stable
